"""empty message

Revision ID: 70f00ff2c2ac
Revises: 1486d57ddfc5
Create Date: 2023-08-10 17:11:44.790552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f00ff2c2ac'
down_revision = '1486d57ddfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=575), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=555), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_result2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=275), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_result2')
    op.drop_table('search_result')
    # ### end Alembic commands ###
