"""empty message

Revision ID: 9a7e79142959
Revises: e7ddb2c94181
Create Date: 2023-08-14 11:04:34.036410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7e79142959'
down_revision = 'e7ddb2c94181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=575), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=555), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_resultf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('images', sa.String(length=2000), nullable=True),
    sa.Column('post_url', sa.String(length=2000), nullable=True),
    sa.Column('time', sa.String(length=2000), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_resultf')
    op.drop_table('search_result')
    # ### end Alembic commands ###
