"""empty message

Revision ID: aecf3dde19d3
Revises: 
Create Date: 2023-08-10 09:19:20.419841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecf3dde19d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=275), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_result2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=275), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_result2')
    op.drop_table('search_result')
    # ### end Alembic commands ###
