"""empty message

Revision ID: cb3e51d6822a
Revises: aa718a51876a
Create Date: 2023-08-12 14:39:04.311497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3e51d6822a'
down_revision = 'aa718a51876a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=575), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=555), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_resultf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('images', sa.String(length=2000), nullable=True),
    sa.Column('post_url', sa.String(length=2000), nullable=True),
    sa.Column('time', sa.String(length=2000), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_resultf')
    op.drop_table('search_result')
    # ### end Alembic commands ###
